name: Feature Request
description: Suggest an idea
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We appreciate your idea to improve ML Playground.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the problem.
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
