"""initial

Revision ID: 08a9ad6066a6
Revises:
Create Date: 2026-06-15 16:25:26.051235

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "08a9ad6066a6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
